### ISSUE TITLE
How to setup the lut on Arduino IDE

### ISSUE THREAD

**Issue by alessiasimone** [e-tinkers/esp32-adc-calibrate#5]
Goodmorning, I recently discovered the problem of non-linearity on my esp-32 which is an Heltec wifi kit V3. Is it possible to get rid of this problem with your code? How can I set up the library on my arduino ide to try to fix the non-linearity? There's some additional library that I should install? or maybe download and installing something from here? Can you please help me initialize the lut?

**Comment by techstudio-design** [comment]
Did you read the README or try the code before posting your question?

**Comment by alessiasimone** [comment]
Goodmorning, yes. It says that I need the driver dac library but i can't find it.

**Comment by e-tinkers** [comment]
It is in the 2nd line of the code (https://github.com/e-tinkers/esp32-adc-calibrate/blob/master/src/main.cpp#L2).
